### ISSUE TITLE
Docker - Cannot Specify Port

### ISSUE THREAD

**Issue by tokenwizard** [Zyphra/Zonos#158]
I have tried running this and it refuses to run because it says it can't find a port in the range 7860-7860 (I have another app using that port). 

It also says you can specify a different port in the environment variable or using the server_port parameter. 

I have updated my docker compose as such:

```
version: '3.8'

services:
  zonos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zonos_container
    runtime: nvidia
    network_mode: "host"
    stdin_open: true
    tty: true
    command: ["python3", "gradio_interface.py", "server_port 7960"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - GRADIO_SHARE=False
      - GRADIO_SERVER_PORT=7960
    ports: 
      - "7960:7960"

```

But I still get the same error:
```
zonos_container  | Traceback (most recent call last):
zonos_container  |   File "/app/gradio_interface.py", line 419, in <module>
zonos_container  |     demo.launch(server_name="0.0.0.0", server_port=7860, share=share)
zonos_container  |   File "/opt/conda/lib/python3.11/site-packages/gradio/blocks.py", line 2570, in launch
zonos_container  |     ) = http_server.start_server(
zonos_container  |         ^^^^^^^^^^^^^^^^^^^^^^^^^
zonos_container  |   File "/opt/conda/lib/python3.11/site-packages/gradio/http_server.py", line 156, in start_server
zonos_container  |     raise OSError(
zonos_container  | OSError: Cannot find empty port in range: 7860-7860. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
zonos_container exited with code 1

```
